services:
  belabox:
    build: .
    # privileged is required to access the GPU, Wi-Fi, bluetooth, etc.
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /sys/fs/cgroup:/sys/fs/cgroup
    devices:
      - /dev/dri:/dev/dri
      - /var/run/dbus/:/var/run/dbus/:z
      - /dev/snd:/dev/snd
      - /dev/shm:/dev/shm
      - /etc/machine-id:/etc/machine-id
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - "8080:80"
